### ISSUE TITLE
Python 3.9 support including sasl 

### ISSUE THREAD

**Issue by potiuk** [python-ldap/python-ldap#413]
Issue description:

Python-ldap does not install for python 3.9 due to sasl dependency.

When we are trying to install python-ldap during the Python 3.9 build, it pulls in sasl dependency which is not py3.9 compliant and it will rather not be. For example thrift-sasl switched to pure-sasl which is pure-python sasl implementation. **https://github.com/cloudera/thrift_sasl/commit/64b723ec6bd99390ae27531804ae91692fa705d7#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7**

We are just about to remove "ldap provider" from Python 3.9 build of "apache airflow" - https://github.com/apache/airflow/pull/15515   because otherwise we can't build the docker image easily

When we try to install Python-ldap in python 3.9 it fails with this stack trace:

```
Running setup.py install for python-ldap: started
    Running setup.py install for python-ldap: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y3uhe43e/python-ldap_49ee3d6c2ffd44049018a8ade2360fa9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y3uhe43e/python-ldap_49ee3d6c2ffd44049018a8ade2360fa9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d8aok4al/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/python-ldap
         cwd: /tmp/pip-install-y3uhe43e/python-ldap_49ee3d6c2ffd44049018a8ade2360fa9/
    Complete output (82 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.linux-x86_64-3.9
    copying Lib/ldapurl.py -> build/lib.linux-x86_64-3.9
    copying Lib/ldif.py -> build/lib.linux-x86_64-3.9
    creating build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/logger.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/filter.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/resiter.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/asyncsearch.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/cidict.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/modlist.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/sasl.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/functions.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/async.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/constants.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/pkginfo.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/ldapobject.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/syncrepl.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/__init__.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/compat.py -> build/lib.linux-x86_64-3.9/ldap
    copying Lib/ldap/dn.py -> build/lib.linux-x86_64-3.9/ldap
    creating build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/ppolicy.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/libldap.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/pwdpolicy.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/sessiontrack.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/vlv.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/openldap.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/pagedresults.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/readentry.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/sss.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/__init__.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/psearch.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/deref.py -> build/lib.linux-x86_64-3.9/ldap/controls
    copying Lib/ldap/controls/simple.py -> build/lib.linux-x86_64-3.9/ldap/controls
    creating build/lib.linux-x86_64-3.9/ldap/extop
    copying Lib/ldap/extop/dds.py -> build/lib.linux-x86_64-3.9/ldap/extop
    copying Lib/ldap/extop/__init__.py -> build/lib.linux-x86_64-3.9/ldap/extop
    copying Lib/ldap/extop/passwd.py -> build/lib.linux-x86_64-3.9/ldap/extop
    creating build/lib.linux-x86_64-3.9/ldap/schema
    copying Lib/ldap/schema/tokenizer.py -> build/lib.linux-x86_64-3.9/ldap/schema
    copying Lib/ldap/schema/models.py -> build/lib.linux-x86_64-3.9/ldap/schema
    copying Lib/ldap/schema/__init__.py -> build/lib.linux-x86_64-3.9/ldap/schema
    copying Lib/ldap/schema/subentry.py -> build/lib.linux-x86_64-3.9/ldap/schema
    creating build/lib.linux-x86_64-3.9/slapdtest
    copying Lib/slapdtest/_slapdtest.py -> build/lib.linux-x86_64-3.9/slapdtest
    copying Lib/slapdtest/__init__.py -> build/lib.linux-x86_64-3.9/slapdtest
    running egg_info
    writing Lib/python_ldap.egg-info/PKG-INFO
    writing dependency_links to Lib/python_ldap.egg-info/dependency_links.txt
    writing requirements to Lib/python_ldap.egg-info/requires.txt
    writing top-level names to Lib/python_ldap.egg-info/top_level.txt
    reading manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    no previously-included directories found matching 'Doc/.build'
    adding license file 'LICENCE'
    writing manifest file 'Lib/python_ldap.egg-info/SOURCES.txt'
    creating build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/README -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/ca.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/ca.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/client.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/client.key -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/client.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/gencerts.sh -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/gennssdb.sh -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/server.conf -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/server.key -> build/lib.linux-x86_64-3.9/slapdtest/certs
    copying Lib/slapdtest/certs/server.pem -> build/lib.linux-x86_64-3.9/slapdtest/certs
    running build_ext
    building '_ldap' extension
    creating build/temp.linux-x86_64-3.9
    creating build/temp.linux-x86_64-3.9/Modules
    gcc -pthread -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -fPIC -DHAVE_SASL -DHAVE_TLS -DHAVE_LIBLDAP_R -DHAVE_LIBLDAP_R -DLDAPMODULE_VERSION=3.3.1 -DLDAPMODULE_AUTHOR=python-ldap project -DLDAPMODULE_LICENSE=Python style -IModules -I/usr/local/include/python3.9 -c Modules/LDAPObject.c -o build/temp.linux-x86_64-3.9/Modules/LDAPObject.o
    Modules/LDAPObject.c:16:10: fatal error: sasl/sasl.h: No such file or directory
     #include <sasl/sasl.h>
              ^~~~~~~~~~~~~
    compilation terminated.
    error: command '/usr/bin/gcc' failed with exit code 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/local/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-y3uhe43e/python-ldap_49ee3d6c2ffd44049018a8ade2360fa9/setup.py'"'"'; __file__='"'"'/tmp/pip-install-y3uhe43e/python-ldap_49ee3d6c2ffd44049018a8ade2360fa9/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-d8aok4al/install-record.txt --single-version-externally-managed --compile --install-headers /usr/local/include/python3.9/python-ldap Check the logs for full command output.
```

**Comment by tiran** [comment]
Your problem is not related to Python 3.9. python-ldap works fine with Python 3.9. python-ldap fails to compile because Cyrus SASL development headers are missing on the system. OpenLDAP's libldap uses Cyrus SASL.

What's your platform and distribution?

**Comment by potiuk** [comment]
Yeah you are right this looks strange but the problem is that it all works fine in Python36/37/38. We build it using buster-slim docker image and it works so far (for years now) using previous python versions. 

We seem to have all the necessary packages installed:

```
           libsasl2-2 \
           libsasl2-dev \ 
           libsasl2-modules \
```

so yeah it looks weird - I agree.

The Docker image we use is here https://github.com/apache/airflow/blob/main/Dockerfile.ci

**Comment by potiuk** [comment]
I realize it's a difficult one to get the whole Airflow (~500 dependencies altogether) - so I might try to extract a simple, reproducible case. If this is something unexpected and strange - please hold on, I might be able to get to the bottom of it.

**Comment by tiran** [comment]
python-ldap builds fine on Python 3.9 and with SASL support on several platforms.

* Ubuntu: https://travis-ci.org/github/python-ldap/python-ldap/jobs/769743051
* Fedora https://koji.fedoraproject.org/koji/buildinfo?buildID=1690274 / https://kojipkgs.fedoraproject.org//packages/python-ldap/3.3.1/4.fc34/data/logs/x86_64/build.log
* I also know for sure that it's building on C9S and RHEL 9 beta

Somehow your C compiler is unable to locate the file. Could you please check if ``/usr/include/sasl/sasl.h`` exists before you invoke python-ldap build?

**Comment by potiuk** [comment]
yeah. Will do tomorrow and let you know

**Comment by potiuk** [comment]
OK. I think it was some caching issue when I tried to build the image.  Closing the issue for now, I will reopen if I find I can reproduce it. Sorry to bother you @tiran
